# JWT configuration
jwt:
  secret: "secure randomness"
  refresh: "secure randomness"

# SMTP configuration
smtp:
  port: 123
  pass: ""
  host: ""
  user: ""
  secure: true

# Email configuration
email:
  client: "nodemailer or courier"

# Polygon variables
polygon:
  frontendUrl: "polygon frontend url"

# Courier configuration
courier:
  token: "courier api token"
  brandId: "courier brand id"

  events:
    VERIFICATION: "courier verification template event id"

# Database configuration
databases:
  redis: "redis connection string"
  postgres: "postgres connection string"
