name: Node CI

on:
  push:
    branches: ["nightly"]
    paths-ignore:
      - "bin/**"
      - "docs/**"
      - "examples/**"
      - "templates/**"
      - "migrations/**"
  pull_request:
    branches: [ nightly ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
